GET http://localhost:8081/api/jokes/retrieve
Accept: application/json

###

GET http://localhost:8081/api/jokes/random/5
Accept: application/json
Authorization: 1 ## userId or username

###

GET http://localhost:8081/api/jokes/stats
Accept: application/json

###
